# Generated by Django 3.0.6 on 2020-05-17 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=7)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='orderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(max_length=300)),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='sales.item')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('items', models.ManyToManyField(to='sales.orderItem')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
