# Generated by Django 3.0.6 on 2020-05-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20200520_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='orderID',
        ),
    ]
