# Generated by Django 3.0.6 on 2020-05-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_order_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
