# Generated by Django 3.0.6 on 2020-05-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20200520_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
