# Generated by Django 3.0.6 on 2020-05-20 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='salesperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.employee'),
        ),
    ]
