# Generated by Django 3.0.6 on 2020-05-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_auto_20200520_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, to='sales.item'),
        ),
    ]
